version: '3.4'
services:
  Frontend0:
    image: gnes/gnes:${GNES_IMG_TAG}
    command: frontend --grpc_port 5566 --port_out 53463 --socket_out PUSH_BIND --port_in
      57908 --socket_in PULL_BIND --dump_route $BENCHMARK_DIR/.data/network.json
    ports:
      - 5566:5566
    volumes:
      - $SHARED_HOST_PATH:/workspace
  Router0:
    image: gnes/gnes:${GNES_IMG_TAG}
    command: >
      route --port_in 53463 --socket_in PULL_CONNECT --port_out 57909
      --socket_out PUSH_CONNECT --host_in Frontend0 --host_out Router1 --yaml_path "!BlockRouter {parameters: {sleep_sec: 1}}"
    deploy:
      replicas: 2
  Router1:
    image: gnes/gnes:${GNES_IMG_TAG}
    command: >
      route --port_in 57909 --socket_in PULL_BIND --port_out 57908
      --socket_out PUSH_CONNECT --host_out Frontend0 --yaml_path "!BaseReduceRouter {parameters: {num_part: 2}}"